= P2Poolv2 Documentation
:page-nav_order: 1
:page-permalink: /
:page-description: Documentation for P2Poolv2, a permissionless, auditable, self-custodial Bitcoin mining pool.

[.fs-6.fw-300]
Mission: Replace pool operators with miners

P2Poolv2 is a permissionless mining pool where miners build block templates,
continuously audit accounting and are paid directly to their wallets.

xref:getting-started/index.adoc[Get started,role="btn btn-primary fs-5 mb-4 mb-md-0 mr-2"]
https://github.com/p2poolv2/p2poolv2[View on GitHub,role="btn fs-5 mb-4 mb-md-0"]

== What is here

Run a node:: Run a node from source and connect your miners, see xref:getting_started.adoc[Getting started]

P2P Network:: How miners join a p2p network to reduce their variance xref:p2p-network-of-miners.adoc[P2P Network of Miners]

Sharechain:: The design of the sharechain, including all the details on how shares are validated and accounted for using PPLNS accounting. See xref:architecture/sharechain.adoc[Sharechain Design]

Payout Mechanisms:: The payout mechanism used so that limitations in
coinbase size do not impact the scalability of the pool. See how miners are paid directly xref:payouts/coinbase.adoc[from bitcoin coinbase] and how small miners can  xref:payouts/marketplace.adoc[Sell shares for payouts]

Dashboards:: The various dashboards available for tracking the local hashrate of the miners attached to a node and for tracking the global sharechain view. See xref:dashboards[Dashboards].

== Elsewhere

* The project site: https://p2poolv2.org[p2poolv2.org]
* Source code: https://github.com/p2poolv2/p2poolv2[github.com/p2poolv2/p2poolv2]
* X: https://x.com/p2poolv2[https://x.com/p2poolv2]
* Wiki: https://github.com/p2poolv2/p2poolv2/wiki[github.com/p2poolv2/p2poolv2/wiki]
* Testnet4 pool and chain explorer: https://testnet4.p2poolv2.org[testnet4.p2poolv2.org]
* Matrix chat: https://matrix.to/#/#p2poolv2:matrix.org[#p2poolv2:matrix.org]
