= Share Validation
:page-parent: Sharechain
:page-nav_order: 20


Shares carry a claimed proof of work and are rewarded for it. The
sharechain validates all shares that are added to the chain so that
the share cannot be rewarded twice for the same proof of work. If
nodes don't validate shares received from other nodes, a sending node
can send the same proof of work for multiple shares and earn multiple
payouts for the same work done. Shares are also validated for their
transactions validity and timestamps enabling verifiable transaction
support in the sharechain.

A share validation covers a number of core validity concerns.

== Proof of Work Meets Pool Difficulty

Payouts depend on proof of work submitted by miners. The pool
difficulty comes from the ASERT algorithm applied over a share's
ancestors and a share's declared target matches what the pool expects
according to ASERT.

Sharechain headers carry all the information to validate ASERT
difficulty of a new share received from a peer. This check can be run
on headers once all their ancestors are available - this is a quirk of
ASERT. The share PoW validation therefore is done in serial once all
headers have been received during initial sync. During normal
operations all ancestors are available, or we wait for them if some
are missing.

== Timestamp Limits

ASERT sets the difficulty from share times and height. Miners are not
be able to manipulate share timestamps that results in lower
difficulty for their shares.

P2Poolv2 uses a tight bound on medium time past (MTP) over 11 blocks
and enforces that a share's timestamp is greater than the MTP, and not
more than 120s ahead of the local clock.

== Unique PoW for Each Share

No two shares can use the same PoW from the bitcoin block to earn more
than one reward for a single PoW. We use share commitments (see
xref:share_commitment.adoc[Share Commitment] on the details on how a
share is committed to a bitcoin header. Once a share is committed to a
bitcoin header and a bitcoin blockhash is found for the current pool
difficulty no other share can embed the given bitcoin header. A
bitcoin header with PoW can only be embedded in a share header it
commits to. Each share has a unique proof of work that no other share
can claim as its own.

== Uncles Follow the Rules

Uncle shares earn rewards and uncles have to follow all of the
validation rules discussed here.

Uncle blocks are fully validated as a normal shareblock. There are
additional rules about how deep an uncle block can be from the nephew
block. Also, nephews are given a bonus reward for including uncles and
uncles are discounted for being not on the main chain.

Each shareblock can have three uncles and each uncle has to be within
three depth of the nephew referring to the uncle. Also, an shareblock
can is included as an uncle only if it has not already an uncle to
another shareblock.

== Bitcoin Payouts Follow the PPLNS Window

All bitcoin coinbases follow the PPLNS window on the sharechain. No
share includes a bitcoin block header with a coinbase in the bitcoin
block that doesn't follow the sharechain PPLNS reward distribution.

P2Poolv2 uses a PPLNS window of shares over the last 120,960 share
blocks, which is number of 10s intervals in two weeks. This period is
selected to allow miners enough time to trade their shares for payment
in bitcoin. This trading is required for paying out smaller miners
with tiny payouts. xref:../payouts/marketplace.adoc[ Sell Shares for
Payouts] page describes the various ways a share can be traded for
bitcoin.

// Nakamoto consensus provides eventual consistency and shares have to
// wait till they are replicated and consensus is formed on their
// confirmation. The coinbase in shareblocks are not spendable until an
// hours worth of blocks have been mined on top of it. This is a much
// smaller limit than bitcoin (~ 1 day), and allows for earlier share
// trading and payouts for shares. Once a share is out of the PPLNS
// window, it is no longer rewarded for work in bitcoin blocks and
// therefore can not be spent/traded any more.

== Share Transactions Are Valid

All shareblock transactions, including the coinbase are valid in terms
of value spent, scripts, spent outputs.

Just like in bitcoin all shareblock transactions are validated for
double spend, the amount being spent so that share value is not
created out of thin air.

== Mine on the Current Bitcoin Chain

The bitcoin header builds on the current bitcoin chain, not an
adversarial fork of bitcoin.

Each shareheader's bitcoin block header (see
xref:sharechain.adoc[Sharechain]) is verified to be reachable from the
parent share's bitcoin block header. This enforces that each share
extending the sharechain is mining on the same bitcoin chain that the
parent share mined on. If there are bitcoin forks attacking the main
chain, shares mining on their blocks are rejected by all nodes. The
bitcoin fork followed by the pool is the one that majority of the
hashrate on the pool is following.

== Bitcoin Blocks Are Not Validated

As seen on <<Mine on Current Bitcoin Chain>> each share builds on the
same chain that the majority of hashrate is following. The bitcoin
block contents are not validated by P2Poolv2 - only the header is
verified to follow the correct bitcoin chain.

The coinbase transaction from the bitcoin block body is verified. Each
shareblock header captures the bitcoin header and shareblock itself
carries the merkle branches of the bitcoin block - this is how we
verify the share commitment and the bitcoin coinbase payout meets the
verifying node's PPLNS window.

Validating full bitcoin blocks will introduce latency to the system
increasing the uncle rate and thus reducing the total capacity of the
pool to handle mining nodes. The details around this are further
discussed in the
<<../handling_known_attacks.adoc#block-withholding-sabotage,Block
Withholding Attack>> section.
